### ISSUE TITLE
acme.sh accesses wrong directory

### ISSUE THREAD

**Issue by achmetinternet** [danb35/deploy-freenas#16]
![Anmerkung 2019-08-06 223514](https://user-images.githubusercontent.com/2337851/62575184-7b065e00-b89a-11e9-9ae5-5fca63052133.png)
This is what I am facing. I believe the freenas.local is wrong but dunno how to change it to the correct one...
![Anmerkung 2019-08-06 222453](https://user-images.githubusercontent.com/2337851/62575141-5ca06280-b89a-11e9-848f-78fce52bf0d1.png)

**Comment by achmetinternet** [comment]
OK, I changed the settings in the deploy_freenas.py file and it said:

root@freenas[~]# /root/deploy-freenas/deploy_freenas.py
Certificate import successful
Certificate list successful
Setting active certificate successful

Now I also have the certificate under System --> Certificates and set under General the protocol to HTTPS but when I access the WebGUI, it still tells me it is an unsecure connection...

Any idea what I am doing wrong?

**Comment by danb35** [comment]
I think I've seen cases where the API method to reload the webserver doesn't work as expected.  Does it work if you run `service nginx reload` at the CLI?

**Comment by achmetinternet** [comment]
service nginx reload
![image](https://user-images.githubusercontent.com/2337851/62583662-697c8080-b8b1-11e9-9205-fcf9ef47fab6.png)

I tried to apply your logic to my Nextcloud jail btw and now I cannot access its GUI anymore :(

**Comment by danb35** [comment]
After doing the `service nginx reload`, are you now able to access the web GUI?  If not, what error are you getting?

> I tried to apply your logic to my Nextcloud jail

Nothing about this script was intended to work with Nextcloud in any way, so it isn't surprising it didn't work.

**Comment by achmetinternet** [comment]
I was able to access the WebGUI before but was thinking my browser would deem it a secure connection given that a certificate was deployed.

**Comment by danb35** [comment]
So what is the certificate error you're seeing?

**Comment by achmetinternet** [comment]
I was expecting to not see the label "not secure" in my browser: 
![image](https://user-images.githubusercontent.com/2337851/62584094-6f736100-b8b3-11e9-8332-ec9fec62f5be.png)

Shouldn't that now be gone?

**Comment by danb35** [comment]
> Shouldn't that now be gone?

No.  You'll get a certificate error if the hostname you're browsing to is not the same as a hostname on the certificate.  If you browse to your actual FQDN (the one you put on the certificate), it may fix the problem.  If it doesn't, I'd need to see the "Weitere Informationen".
