### ISSUE TITLE
Add cleanup of old certificates

### ISSUE THREAD

**Issue by SigLinJo** [danb35/deploy-freenas#18]
Found this post [https://www.ixsystems.com/community/threads/using-freenas-api-to-delete-old-certificates.81918/](url) when trying to get rid of the 20 + alerts of expired certificates I got after upgrading to FreeNAS 11.3. I don't totally understand the code and therefore I can't really include the cleanup script in deploy-freenas. As everyone using deploy-freenas for any length of time in FreeNAS 11.3 would wan't to delete expired certificates I thought maybe someone with better knowlege of python and FreeNAS could come up with an automated way to keep only valid certificates in FreeNAS...

The script works well otherwise. I have my reverse proxy jail issue the certificates and the script then imports them to FreeNAS. Thank you!

**Comment by danb35** [comment]
Fixed with #19.
