### ISSUE TITLE
WebUI doesn't restart

### ISSUE THREAD

**Issue by GTAXL** [danb35/deploy-freenas#25]
Hello, the script was able to add the cert and make it active but the connection would still use the existing cert, even after clearing cache. I also noticed the script didn't remove the initial webui cert. It only removes certs that were added via the script. I had to go into the webui, switch back to the old cert, it would prompt to restart the webui, then switch back to the new cert, it would prompt to restart the webserver, then it would show the new cert. I then deleted the old cert. You should also add checking for the webui restart, it doesn't show successful or failed.

**Comment by simmonmt** [comment]
My API docs (TrueNAS beta 2) say /api/v2.0/system/general/ui_restart is a GET -- not a POST. Changing the source to use `session.get` for `ui_restart` made it start working for me.
