### ISSUE TITLE
Readme suggests --deploy-hook. Does not work. --reloadcmd does. Please update readme.

### ISSUE THREAD

**Issue by jkhii** [danb35/deploy-freenas#27]
I tried to set this up and following the readme file tried to specify deploy-freenas as a deploy hook in acme.sh. This did not work. I got the following error message:

jhays@moya:~/.acme.sh % acme.sh --deploy -d moya.jkhfamily.net --deploy-hook "/mnt/MoyaV1/home/jhays/.acme.sh/deploy_freenas.py"
[Mon Aug 31 23:02:02 CDT 2020] The deploy hook /mnt/MoyaV1/home/jhays/.acme.sh/deploy_freenas.py is not found.

I was able to get it to work using --reloadcmd. See below:

jhays@moya:~/.acme.sh/moya.jkhfamily.net % acme.sh --install-cert -d moya.jkhfamily.net --reloadcmd "/mnt/MoyaV1/home/jhays/.acme.sh/deploy_freenas.py" 
[Mon Aug 31 23:28:36 CDT 2020] Run reload cmd: /mnt/MoyaV1/home/jhays/.acme.sh/deploy_freenas.py
Certificate import successful
Certificate list successful
Setting active certificate successful
Deleting certificate letsencrypt-2020-08-31-230754 successful
[Mon Aug 31 23:28:43 CDT 2020] Reload success

I suggest updating the Readme file.

**Comment by ianmtaylor1** [comment]
I have experienced the same issue.

deploy-freenas commit: 2066feb
acme.sh version: 2.8.7
