### ISSUE TITLE
deploy_freenas.py : No such file or directory "/root/acme.sh/acmejail/acmejail.key"

### ISSUE THREAD

**Issue by achillesdakin** [danb35/deploy-freenas#32]
After running : acme.sh --issue -d ravendellnas.zapto.org --standalone --reloadcmd "~/deploy-freenas/deploy_freenas.py"

Everything works except at the end it cannot find the file "deploy_freenas.py" , so i went to go manually run it with "python deploy_freenas.py' which deploys the error :

No such file or directory "/root/acme.sh/acmejail/acmejail.key"

**Comment by danb35** [comment]
A couple of points:

* You should specify the reload command with an absolute path.  If you downloaded the script into /root/, `reloadcmd` would be set to `/root/deploy-freenas/deploy_freenas.py`.  Adjust as needed, but use the absolute path.
* The script uses the hostname of the system it's running on to determine the default paths to the cert and the private key.  When it's running on the FreeNAS/TrueNAS system itself (which it can do when using DNS validation, but it can't if you're using HTTP validation as you are), this results in suitable paths.  In your case, you'll need to set `cert_fqdn` appropriately in `deploy_config`.

**Comment by achillesdakin** [comment]
Thanks , I have now done both.
Unfortunately I have reached a limit for certificate requests so will need to wait a while I suppose to try again.

**Comment by danb35** [comment]
You could use the `--test` flag to request the cert from the Let's Encrypt test server.  It won't give you a trusted cert, but it will validate that everything is working properly, and the rate limits are higher.  `acme.sh --issue -d ravendellnas.zapto.org --test --standalone --reloadcmd "/path/to/deploy_freenas.py"`

**Comment by achillesdakin** [comment]
Great idea, this is outcome - 
<img width="1440" alt="Screenshot 2020-11-13 at 00 44 51" src="https://user-images.githubusercontent.com/40032346/99014026-b554b580-2549-11eb-8d41-60e46024849a.png">

**Comment by danb35** [comment]
So we're back to needing the correct path to the deploy_freenas script.  You need to specify that path in the `acme.sh` command.

**Comment by achillesdakin** [comment]
file location works now, next problem, sorry there's endless errors






Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.7/http/client.py", line 1277, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1323, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1272, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1032, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 972, in send
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 182, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x802399110>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v2.0/certificate/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x802399110>: Failed to establish a new connection: [Errno 61] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/deploy-freenas/deploy_freenas.py", line 91, in <module>
    "privatekey": priv_key,
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v2.0/certificate/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x802399110>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Fri Nov 13 21:15:23 GMT 2020] Reload error for :

**Comment by danb35** [comment]
Looks like you need to set `connect_host` in `deploy_config`.  Consult the README.

**Comment by achillesdakin** [comment]
I set it to ravendellnas.zapto.org but still get:

HTTPConnectionPool(host='ravendellnas.zapto.org', port=80): Max retries exceeded with url: /api/v2.0/certificate/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x80239b090>: Failed to establish a new connection: [Errno 61] Connection refused'))

**Comment by danb35** [comment]
Does the jail correctly resolve the IP for that FQDN?  From inside the jail, what's the output of `host ravendellnas.zapto.org`?

**Comment by achillesdakin** [comment]
Yes it does

**Comment by achillesdakin** [comment]
It resolves to the correct public ip

**Comment by danb35** [comment]
That's your problem--it needs to resolve to the private IP.  Or just use the private IP address.

**Comment by achillesdakin** [comment]
Outside of obtaining this certificate, is it a problem that it doesn't resolve to the private IP address?
Thank you, I will try that

**Comment by achillesdakin** [comment]
I now have the certificate but, the webgui is still not "secure"

**Comment by danb35** [comment]
What is the exact error?

**Comment by achillesdakin** [comment]
I set the connect_host to the private ip and it all worked, no errors. But the webgui still states unsecure

**Comment by danb35** [comment]
Was my question unclear?  What's the exact issue you're seeing?  There are about a dozen reasons it could be "insecure."

**Comment by achillesdakin** [comment]
Oh sorry
<img width="357" alt="Screenshot 2020-11-23 at 18 29 46" src="https://user-images.githubusercontent.com/40032346/100009205-7551c600-2dc6-11eb-988b-3c2ab078b4a1.png">
<img width="501" alt="Screenshot 2020-11-23 at 18 29 56" src="https://user-images.githubusercontent.com/40032346/100009210-771b8980-2dc6-11eb-8dd1-6af3279057db.png">

**Comment by danb35** [comment]
Then an error is to be expected.  The name you're trying to connect to (the IP address) doesn't appear on the cert.

**Comment by achillesdakin** [comment]
I don't think lets encrypt issue certs to ips, do the think the problem could be because the FQDN doesn't resolve to the private IP?

**Comment by danb35** [comment]
> do the think the problem could be because the FQDN doesn't resolve to the private IP?

This is exactly the problem.

**Comment by achillesdakin** [comment]
Thanks for your help, I'm not sure how to resolve this.

**Comment by DasSkelett** [comment]
You need to enter the FQDN in your browser for the browser to see the cert as valid, since - as you said - Let's Encrypt's certs only apply to domain names.

For that your FQDN needs to properly resolve inside your home network. You have three options:

1) Setup [split DNS](https://en.wikipedia.org/wiki/Split-horizon_DNS): Clients outside your network need to get the public address when resolving the FQDN, and for clients inside your network it needs to resolve to the private address.  
2) Setup [NAT reflection/hairpinning](https://en.wikipedia.org/wiki/Hairpinning): this makes the router analyse your port-forwarding rules, and redirect packets coming from inside the network targeting the public address  to the respective internal address (+port), as if they had come from outside.  
3) Just use IPv6 already. Makes all these hacks obsolete.

**Comment by achillesdakin** [comment]
Great! So you recommend IPv6.

**Comment by achillesdakin** [comment]
How should I set this up? I can't find any answers elsewhere. Thanks
