### ISSUE TITLE
strptime() argument 1 must be str, not None

### ISSUE THREAD

**Issue by oasisck** [danb35/deploy-freenas#34]
Hi, I updated Freenas to Truenas and your script to the latest version.
I had an error : 
```
Certificate import successful
Certificate list successful
Setting active certificate successful
Traceback (most recent call last):
  File "/.../.../deploy_freenas.py", line 171, in <module>
    issued_date = datetime.strptime(cert_data['from'], "%c")
TypeError: strptime() argument 1 must be str, not None
```
thanks

**Comment by danb35** [comment]
With the latest updates, I'm not seeing this error.  Can you confirm it's fixed with the current version of the script?

**Comment by oasisck** [comment]
I switched to another distrib since, so dunno :)
I close the issue.

**Comment by TotalNormal2** [comment]
I got the same issue. It was caused by a pending "certificate signing request", which will be listed, but contains no "from".
