### ISSUE TITLE
TrueNas Scale compatible ? 

### ISSUE THREAD

**Issue by LoulouCrypto** [danb35/deploy-freenas#46]
Hello 

Is that method is compatible with truenas scale ? 

Thx

**Comment by danb35** [comment]
I have no idea.  SCALE hadn't even been announced when it was developed, and I haven't tried it.  I think the APIs are supposed to be the same, and if that's true, it should work, but there hasn't been any testing as yet.  Feel free to give it a try.

**Comment by LoulouCrypto** [comment]
Hello 
I try the script and i have this error : 

root@Server[~/deploy-freenas]# python3 deploy_freenas.py
Traceback (most recent call last):
  File "/root/deploy-freenas/deploy_freenas.py", line 81, in <module>
    with open(PRIVATEKEY_PATH, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.acme.sh/........

**Comment by danb35** [comment]
That message indicates that certificate files aren't where `acme.sh` would put them.  Do you have a cert on that machine?  If so, did you obtain it using acme.sh?  If you have a cert that you got in some other way, you'll need to tell the script where it is--instructions for that are in the README.

**Comment by yajrendrag** [comment]
just closing the loop on this - i tried this on scale and it works fine.
