### ISSUE TITLE
Issue generating certificate via google Cloud DNS API

### ISSUE THREAD

**Issue by hatakora62** [danb35/deploy-freenas#48]
I have followed the docs and instructions and everything. Setup gcloud on my truenas box and connected my account. When i run the script to generate the cert i am getting the error below

WARNING: The following filter keys were not present in any resource : dnsName, visibility
[Wed Feb 16 23:39:56 PST 2022] _dns_gcloud_find_zone: Can't find a matching managed zone! Perhaps wrong project or gcloud credentials?
[Wed Feb 16 23:39:56 PST 2022] Error add txt for domain:_acme-challenge.mydomain.co

But i can see in my Gcloud account APi monitoring that the calls are coming through so it is not a credential issue. What am i doing wrong?

**Comment by danb35** [comment]
I'm afraid I don't have any experience with Google's Cloud DNS.  It seems this would be better directed to the support channels for whatever ACME client you're using (e.g., https://github.com/acmesh-official/acme.sh/issues)
