### ISSUE TITLE
Error when running script

### ISSUE THREAD

**Issue by niklas2233** [danb35/deploy-freenas#53]
hey when i run the scipt i get error on line 81 <module>
    with open(PRIVATEKEY_PATH, 'r') as file:

![fyaGWvB](https://user-images.githubusercontent.com/33903786/172092653-df344dc5-4efc-4792-a7a9-cba56828650c.png)

**Comment by DasSkelett** [comment]
You need to set the `privkey_path` to wherever your private key is actually stored. See the example config in the README.

**Comment by danb35** [comment]
The script assumes you're using acme.sh and that the cert files will be stored in its default locations.  If they're anywhere else, as @DasSkelett says, you'll need to specify the paths in the config file.
