### ISSUE TITLE
error running scritp on truenas scale

### ISSUE THREAD

**Issue by niklas2233** [danb35/deploy-freenas#56]
so when i run the script i get this error but i can manually use the files and add the cert in the web gui.
i have specified the fqdn and the paths to the private key and the path to fullchain

![xW4vEZ3](https://user-images.githubusercontent.com/33903786/184537028-548ae972-7cbb-4379-aed6-281b517d61dc.png)

**Comment by DasSkelett** [comment]
Looks like your web UI is not listening on port 80. Either enable it, or try with `port = 443` and `protocol = https://`.
See the [example configuration](https://github.com/danb35/deploy-freenas/blob/master/deploy_config.example) for all available options.

**Comment by niklas2233** [comment]
omg im retarded. changed the web gui to 81 since treafik is using 80 but missed that. thanks for the quick response
