### ISSUE TITLE
--reloadcmd "/path/to/deploy_freenas.py" no longer works

### ISSUE THREAD

**Issue by adorobis** [danb35/deploy-freenas#59]
For some strange reason `--reloadcmd "/path/to/deploy_freenas.py"` does not work anymore and I had to change the command to `python3 /path/to/deploy_freenas.py`. I think this is after upgrading to TrueNAS 13.

**Comment by Tuckie** [comment]
Did you still have execute permissions on deploy_freenas.py?

You may need to `chmod +x deploy_freenas.py`

**Comment by adorobis** [comment]
It was a different problem. As I was updating the deploy_freenas.py I have probably made an empty file in Windows notepad++ and it was saved with Windows EOL (CR LF). After converting it to Unix (LF) it works again.
