### ISSUE TITLE
Deletion of old cert fails

### ISSUE THREAD

**Issue by Tuckie** [danb35/deploy-freenas#65]
Minor typo, but as a result, old certs will never be deleted.

The double quotes should be removed around `CERT_BASE_NAME`

```py
      if cert_data['name'].startswith("CERT_BASE_NAME"):
```

https://github.com/danb35/deploy-freenas/blob/master/deploy_freenas.py#L216

**Comment by adorobis** [comment]
Many thanks for spotting that. Fix has been provided.
