### ISSUE TITLE
Add support for deploying certs to Nextcloud instance hosted on TrueNAS (Core)

### ISSUE THREAD

**Issue by ccman32** [danb35/deploy-freenas#67]
I am using acme.sh on my TrueNAS Core system to obtain a wildcard cert which I then use for the UI and WebDAV. However, I recently also installed the Nextcloud plugin for which I also want to use my cert. Would it be possible to add an option to this script to copy the obtained cert into the Nextcloud jail, or are there any reasons for not doing this?

**Comment by danb35** [comment]
> Would it be possible to add an option to this script to copy the obtained cert into the Nextcloud jail

No, for a  few reasons:

* It's just fundamentally out of the scope of what this script's intended to do.  Sure, it's technically possible--just about anything is possible in a script with enough knowledge and motivation--but that's a fundamentally different problem than the  one this script is designed to solve.
* Plugins on CORE are, in the words of Kris Moore (iX' CTO), "all but deprecated" and a "path to sadness."  They should not be used under any circumstances, and I don't want to encourage their use.  For those comments and related discussion, see:
https://www.truenas.com/community/threads/ixsystems-when-are-you-going-to-stop-pretending-that-core-has-usable-plugins.104355/
* IMNSHO, there's a much better way to put Nextcloud into a jail, which (among other things) automates all the certificate stuff:
https://github.com/danb35/freenas-iocage-nextcloud

**Comment by ccman32** [comment]
Thank you for the detailed response! First of all, I already suspected that my request might be out of scope for this script, but I thought it doesn't hurt to ask.

I also wasn't aware that plugins on Core should be avoided at all, so thank you for the heads-up. TrueNAS sometimes just seems like a big minefield to me with tons of things you "can" do but many of them being, in Kris Moore's words, a "path to sadness".

Anyway, as I just started working with the Nextcloud plugin, I'll certainly check out freenas-iocage-nextcloud.

**Comment by adorobis** [comment]
As much as I would agree that it might not make sense to implement it in this scrip, deploying a cert to a Nextcloud jail is actually quite simple. Here is my shell script that does it. I also deploy it to many other places (jails, other systems - e.g. debian, or even a router).
```
    # copy certificates to nextcloud jail
    cp /etc/certificates/new/letsencrypt.key /mnt/Dane/iocage/jails/nc/root/etc/ssl/cert.key
    cp /etc/certificates/new/letsencrypt.crt /mnt/Dane/iocage/jails/nc/root/etc/ssl/cert.crt
	
    # restart nextcloud web server
    iocage exec nc service nginx restart
```
Here is my full script if you are interested in more than just Nextcloud
